"""empty message

Revision ID: ef3b3ee21578
Revises: 
Create Date: 2026-03-09 14:49:56.196081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef3b3ee21578'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('compile_cmd', sa.String(), nullable=True),
    sa.Column('run_cmd', sa.String(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submission_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_batches_token'), 'submission_batches', ['token'], unique=True)
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.Uuid(), nullable=False),
    sa.Column('source_code', sa.Text(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('stdin', sa.Text(), nullable=True),
    sa.Column('expected_output', sa.Text(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('compile_output', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('time', sa.Float(), nullable=True),
    sa.Column('wall_time', sa.Float(), nullable=True),
    sa.Column('memory', sa.Integer(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('exit_signal', sa.Integer(), nullable=True),
    sa.Column('cpu_time_limit', sa.Float(), nullable=False),
    sa.Column('cpu_extra_time', sa.Float(), nullable=False),
    sa.Column('wall_time_limit', sa.Float(), nullable=False),
    sa.Column('memory_limit', sa.Integer(), nullable=False),
    sa.Column('stack_limit', sa.Integer(), nullable=False),
    sa.Column('max_file_size', sa.Integer(), nullable=False),
    sa.Column('max_processes_and_or_threads', sa.Integer(), nullable=False),
    sa.Column('enable_per_process_and_thread_time_limit', sa.Boolean(), nullable=True),
    sa.Column('enable_per_process_and_thread_memory_limit', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('batch_token', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['batch_token'], ['submission_batches.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_token'), 'submissions', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_token'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_submission_batches_token'), table_name='submission_batches')
    op.drop_table('submission_batches')
    op.drop_table('languages')
    # ### end Alembic commands ###
